// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: 001_appointments.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createAppointment = `-- name: CreateAppointment :one
INSERT INTO appointments (id, created_at, first_name, last_name, email, mobile_phone, requested_date, is_emergency, description, appointment_type, is_scheduled, scheduled_date, created_by, scheduled_by, is_cancelled, requested_time, scheduled_time, practice_id, modified_at)
VALUES (
    gen_random_uuid, 
    NOW(),
    $1, 
    $2, 
    $3, 
    $4,
    $5, 
    $6, 
    $7, 
    $8, 
    $9, 
    $10, 
    $11, 
    $12, 
    $13, 
    $14, 
    $15, 
    $16, 
    NOW()
)
RETURNING id, first_name, last_name, email, mobile_phone, requested_date, is_emergency, description, appointment_type, is_scheduled, scheduled_date, created_by, scheduled_by, is_cancelled, requested_time, scheduled_time, practice_id, created_at, modified_at
`

type CreateAppointmentParams struct {
	FirstName       string
	LastName        string
	Email           string
	MobilePhone     string
	RequestedDate   time.Time
	IsEmergency     sql.NullBool
	Description     sql.NullString
	AppointmentType sql.NullString
	IsScheduled     sql.NullBool
	ScheduledDate   sql.NullTime
	CreatedBy       uuid.NullUUID
	ScheduledBy     uuid.NullUUID
	IsCancelled     sql.NullBool
	RequestedTime   string
	ScheduledTime   sql.NullTime
	PracticeID      uuid.UUID
}

func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRowContext(ctx, createAppointment,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.MobilePhone,
		arg.RequestedDate,
		arg.IsEmergency,
		arg.Description,
		arg.AppointmentType,
		arg.IsScheduled,
		arg.ScheduledDate,
		arg.CreatedBy,
		arg.ScheduledBy,
		arg.IsCancelled,
		arg.RequestedTime,
		arg.ScheduledTime,
		arg.PracticeID,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.MobilePhone,
		&i.RequestedDate,
		&i.IsEmergency,
		&i.Description,
		&i.AppointmentType,
		&i.IsScheduled,
		&i.ScheduledDate,
		&i.CreatedBy,
		&i.ScheduledBy,
		&i.IsCancelled,
		&i.RequestedTime,
		&i.ScheduledTime,
		&i.PracticeID,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
