// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Appointment struct {
	ID              uuid.UUID
	FirstName       string
	LastName        string
	Email           string
	MobilePhone     string
	RequestedDate   time.Time
	RequestedTime   string
	IsEmergency     bool
	Description     *string
	AppointmentType *string
	IsScheduled     bool
	ScheduledDate   *time.Time
	ScheduledTime   *string
	PracticeID      uuid.UUID
	CreatedBy       *uuid.UUID
	ScheduledBy     *uuid.UUID
	IsCancelled     bool
	CreatedAt       time.Time
	ModifiedAt      time.Time
}

type Practice struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	ModifiedAt    time.Time
	Name          string
	City          string
	Phone         string
	Email         string
	Owner         *uuid.UUID
	PracticeCode  *string
	Logo          *string
	StreetAddress *string
	Facebook      *string
	Instagram     *string
	Website       *string
}
