// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Appointment struct {
	ID              uuid.UUID
	FirstName       string
	LastName        string
	Email           string
	MobilePhone     string
	RequestedDate   time.Time
	IsEmergency     sql.NullBool
	Description     sql.NullString
	AppointmentType sql.NullString
	IsScheduled     sql.NullBool
	ScheduledDate   sql.NullTime
	CreatedBy       uuid.NullUUID
	ScheduledBy     uuid.NullUUID
	IsCancelled     sql.NullBool
	RequestedTime   sql.NullString
	ScheduledTime   sql.NullTime
	PracticeID      uuid.NullUUID
	CreatedAt       sql.NullTime
	ModifiedAt      sql.NullTime
}
