// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: practices.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPractice = `-- name: CreatePractice :one
INSERT INTO practices (name, city, phone, email, owner, practice_code, logo, street_address, facebook, instagram, website)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
RETURNING id, created_at, modified_at, name, city, phone, email, owner, practice_code, logo, street_address, facebook, instagram, website
`

type CreatePracticeParams struct {
	Name          string
	City          string
	Phone         string
	Email         string
	Owner         *uuid.UUID
	PracticeCode  *string
	Logo          *string
	StreetAddress *string
	Facebook      *string
	Instagram     *string
	Website       *string
}

func (q *Queries) CreatePractice(ctx context.Context, arg CreatePracticeParams) (Practice, error) {
	row := q.db.QueryRow(ctx, createPractice,
		arg.Name,
		arg.City,
		arg.Phone,
		arg.Email,
		arg.Owner,
		arg.PracticeCode,
		arg.Logo,
		arg.StreetAddress,
		arg.Facebook,
		arg.Instagram,
		arg.Website,
	)
	var i Practice
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Name,
		&i.City,
		&i.Phone,
		&i.Email,
		&i.Owner,
		&i.PracticeCode,
		&i.Logo,
		&i.StreetAddress,
		&i.Facebook,
		&i.Instagram,
		&i.Website,
	)
	return i, err
}

const getPractice = `-- name: GetPractice :one
SELECT id, created_at, modified_at, name, city, phone, email, owner, practice_code, logo, street_address, facebook, instagram, website FROM practices
WHERE ID = $1
`

func (q *Queries) GetPractice(ctx context.Context, id uuid.UUID) (Practice, error) {
	row := q.db.QueryRow(ctx, getPractice, id)
	var i Practice
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Name,
		&i.City,
		&i.Phone,
		&i.Email,
		&i.Owner,
		&i.PracticeCode,
		&i.Logo,
		&i.StreetAddress,
		&i.Facebook,
		&i.Instagram,
		&i.Website,
	)
	return i, err
}

const getPractices = `-- name: GetPractices :many
SELECT id, created_at, modified_at, name, city, phone, email, owner, practice_code, logo, street_address, facebook, instagram, website FROM practices
`

func (q *Queries) GetPractices(ctx context.Context) ([]Practice, error) {
	rows, err := q.db.Query(ctx, getPractices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Practice
	for rows.Next() {
		var i Practice
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.Name,
			&i.City,
			&i.Phone,
			&i.Email,
			&i.Owner,
			&i.PracticeCode,
			&i.Logo,
			&i.StreetAddress,
			&i.Facebook,
			&i.Instagram,
			&i.Website,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePractice = `-- name: UpdatePractice :one
UPDATE practices
SET
    name = COALESCE($1, name),
    city = COALESCE($2, city),
    phone = COALESCE($3, phone),
    email = COALESCE($4, email),
    owner = COALESCE($5, owner),
    practice_code = COALESCE($6, practice_code),
    logo = COALESCE($7, logo),
    street_address = COALESCE($8, street_address),
    facebook = COALESCE($9, facebook),
    instagram = COALESCE($10, instagram),
    website = COALESCE($11, website),
    modified_at = NOW()
WHERE id = $12
RETURNING id, created_at, modified_at, name, city, phone, email, owner, practice_code, logo, street_address, facebook, instagram, website
`

type UpdatePracticeParams struct {
	Name          string
	City          string
	Phone         string
	Email         string
	Owner         *uuid.UUID
	PracticeCode  *string
	Logo          *string
	StreetAddress *string
	Facebook      *string
	Instagram     *string
	Website       *string
	ID            uuid.UUID
}

func (q *Queries) UpdatePractice(ctx context.Context, arg UpdatePracticeParams) (Practice, error) {
	row := q.db.QueryRow(ctx, updatePractice,
		arg.Name,
		arg.City,
		arg.Phone,
		arg.Email,
		arg.Owner,
		arg.PracticeCode,
		arg.Logo,
		arg.StreetAddress,
		arg.Facebook,
		arg.Instagram,
		arg.Website,
		arg.ID,
	)
	var i Practice
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Name,
		&i.City,
		&i.Phone,
		&i.Email,
		&i.Owner,
		&i.PracticeCode,
		&i.Logo,
		&i.StreetAddress,
		&i.Facebook,
		&i.Instagram,
		&i.Website,
	)
	return i, err
}
