// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    first_name,
    last_name, 
    email,
    mobile_phone,
    practice_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, created_at, modified_at, first_name, last_name, mobile_phone, email, practice_id, role, is_active, avatar_url
`

type CreateUserParams struct {
	FirstName   string
	LastName    string
	Email       string
	MobilePhone string
	PracticeID  uuid.UUID
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.MobilePhone,
		arg.PracticeID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.FirstName,
		&i.LastName,
		&i.MobilePhone,
		&i.Email,
		&i.PracticeID,
		&i.Role,
		&i.IsActive,
		&i.AvatarUrl,
	)
	return i, err
}

const getUser = `-- name: GetUser :one

SELECT id, created_at, modified_at, first_name, last_name, mobile_phone, email, practice_id, role, is_active, avatar_url from users WHERE ID = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.FirstName,
		&i.LastName,
		&i.MobilePhone,
		&i.Email,
		&i.PracticeID,
		&i.Role,
		&i.IsActive,
		&i.AvatarUrl,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one

UPDATE users
SET
    first_name =COALESCE($1, first_name),
    last_name =COALESCE($2, last_name),
    email =COALESCE($3, email),
    mobile_phone =COALESCE($4, mobile_phone),
    role = COALESCE($5, role),
    is_active = COALESCE($6, is_active),
    avatar_url = COALESCE($7, avatar_url)
WHERE id = $8
RETURNING id, created_at, modified_at, first_name, last_name, mobile_phone, email, practice_id, role, is_active, avatar_url
`

type UpdateUserParams struct {
	FirstName   *string
	LastName    *string
	Email       *string
	MobilePhone *string
	Role        NullUserRole
	IsActive    *bool
	AvatarUrl   *string
	ID          uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.MobilePhone,
		arg.Role,
		arg.IsActive,
		arg.AvatarUrl,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.FirstName,
		&i.LastName,
		&i.MobilePhone,
		&i.Email,
		&i.PracticeID,
		&i.Role,
		&i.IsActive,
		&i.AvatarUrl,
	)
	return i, err
}
